language: python

python:
  - "3.5.2"

install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

before_script:
  - psql -c "CREATE ROLE ridemyway WITH SUPERUSER LOGIN PASSWORD 'ridemyway';" -U postgres
  - psql -c "CREATE DATABASE ridemyway;" -U postgres

script: 
  - nosetests tests/testUserAccount.py --with-coverage

after_success:
  - coveralls